#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidadorDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AX_Migracao_Staging")]
	public partial class AX_Migracao_StagingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertstg_Cliente(stg_Cliente instance);
    partial void Updatestg_Cliente(stg_Cliente instance);
    partial void Deletestg_Cliente(stg_Cliente instance);
    partial void Insertstg_Fornecedore(stg_Fornecedore instance);
    partial void Updatestg_Fornecedore(stg_Fornecedore instance);
    partial void Deletestg_Fornecedore(stg_Fornecedore instance);
    #endregion
		
		public AX_Migracao_StagingDataContext() : 
				base(global::ValidadorDados.Properties.Settings.Default.AX_Migracao_StagingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AX_Migracao_StagingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AX_Migracao_StagingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AX_Migracao_StagingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AX_Migracao_StagingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<stg_Cliente> stg_Clientes
		{
			get
			{
				return this.GetTable<stg_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<stg_Fornecedore> stg_Fornecedores
		{
			get
			{
				return this.GetTable<stg_Fornecedore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stg_Clientes")]
	public partial class stg_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegistroIDMig;
		
		private string _AccountNum;
		
		private string _OldAccountNum;
		
		private string _CustGroup;
		
		private string _LanguageId;
		
		private string _Currency;
		
		private string _CustClassificationId;
		
		private string _Name;
		
		private string _PartyType;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _NameAlias;
		
		private string _LocationRole;
		
		private string _ZipCode;
		
		private string _Street;
		
		private string _StreetNumber;
		
		private string _BuildingCompliment;
		
		private string _PostBox;
		
		private string _City;
		
		private string _DistrictName;
		
		private string _State;
		
		private string _CountryRegionId;
		
		private string _TaxGroup;
		
		private string _CNPJCPFNum_BR;
		
		private string _IENum_BR;
		
		private string _StatisticsGroup;
		
		private string _ContactPersonId;
		
		private string _LineOfBusinessId;
		
		private string _SegmentId;
		
		private string _SubsegmentId;
		
		private string _CompanyChainId;
		
		private string _SalesDistrictId;
		
		private string _Blocked;
		
		private string _MandatoryCreditLimit;
		
		private string _CreditRating;
		
		private string _CreditMax;
		
		private string _MarkupGroup;
		
		private string _InventSiteId;
		
		private string _InventLocation;
		
		private string _CustItemGroupId;
		
		private string _CommissionGroup;
		
		private string _SalesGroup;
		
		private string _SalesPoolId;
		
		private string _MultiLineDisc;
		
		private string _EndDisc;
		
		private string _PriceGroup;
		
		private string _LineDisc;
		
		private string _PaymTermId;
		
		private string _PaymMode;
		
		private string _PaymSpec;
		
		private string _PaymSched;
		
		private string _PaymDayId;
		
		private string _CashDisc;
		
		private string _BankAccount;
		
		private string _FineCode_BR;
		
		private string _InterestCode_BR;
		
		private string _InvoiceAccount;
		
		private string _InvoiceAddress;
		
		private string _numberSequenceGroup;
		
		private string _TaxWithholdCalculate_TH;
		
		private string _TaxWithholdGroup_TH;
		
		private string _DlvTerm;
		
		private string _DlvMode;
		
		private string _DlvReason;
		
		private string _DestinationCodeId;
		
		private string _VATNum;
		
		private string _InclTax;
		
		private string _CustFinalUser_BR;
		
		private string _ICMSContributor_BR;
		
		private string _ServiceCodeOnDlvAddress_BR;
		
		private string _CCMNum_BR;
		
		private string _CNAE_BR;
		
		private string _Suframa_BR;
		
		private string _SuframaNumber_BR;
		
		private string _SuframaPISCOFINS_BR;
		
		private string _GenerateIncomingFiscalDocument_BR;
		
		private string _MainContactWorkerPartyName;
		
		private string _MainContactWorkerPartyNumber;
		
		private string _MainContactWorkerPersonnelNumber;
		
		private string _Phone;
		
		private string _PhoneName;
		
		private string _DefaultDimensionStr;
		
		private string _TaxWithholdCalculate_IN;
		
		private string _Email;
		
		private string _EmailName;
		
		private string _URL;
		
		private string _UrlName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistroIDMigChanging(int value);
    partial void OnRegistroIDMigChanged();
    partial void OnAccountNumChanging(string value);
    partial void OnAccountNumChanged();
    partial void OnOldAccountNumChanging(string value);
    partial void OnOldAccountNumChanged();
    partial void OnCustGroupChanging(string value);
    partial void OnCustGroupChanged();
    partial void OnLanguageIdChanging(string value);
    partial void OnLanguageIdChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnCustClassificationIdChanging(string value);
    partial void OnCustClassificationIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPartyTypeChanging(string value);
    partial void OnPartyTypeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnNameAliasChanging(string value);
    partial void OnNameAliasChanged();
    partial void OnLocationRoleChanging(string value);
    partial void OnLocationRoleChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnStreetNumberChanging(string value);
    partial void OnStreetNumberChanged();
    partial void OnBuildingComplimentChanging(string value);
    partial void OnBuildingComplimentChanged();
    partial void OnPostBoxChanging(string value);
    partial void OnPostBoxChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryRegionIdChanging(string value);
    partial void OnCountryRegionIdChanged();
    partial void OnTaxGroupChanging(string value);
    partial void OnTaxGroupChanged();
    partial void OnCNPJCPFNum_BRChanging(string value);
    partial void OnCNPJCPFNum_BRChanged();
    partial void OnIENum_BRChanging(string value);
    partial void OnIENum_BRChanged();
    partial void OnStatisticsGroupChanging(string value);
    partial void OnStatisticsGroupChanged();
    partial void OnContactPersonIdChanging(string value);
    partial void OnContactPersonIdChanged();
    partial void OnLineOfBusinessIdChanging(string value);
    partial void OnLineOfBusinessIdChanged();
    partial void OnSegmentIdChanging(string value);
    partial void OnSegmentIdChanged();
    partial void OnSubsegmentIdChanging(string value);
    partial void OnSubsegmentIdChanged();
    partial void OnCompanyChainIdChanging(string value);
    partial void OnCompanyChainIdChanged();
    partial void OnSalesDistrictIdChanging(string value);
    partial void OnSalesDistrictIdChanged();
    partial void OnBlockedChanging(string value);
    partial void OnBlockedChanged();
    partial void OnMandatoryCreditLimitChanging(string value);
    partial void OnMandatoryCreditLimitChanged();
    partial void OnCreditRatingChanging(string value);
    partial void OnCreditRatingChanged();
    partial void OnCreditMaxChanging(string value);
    partial void OnCreditMaxChanged();
    partial void OnMarkupGroupChanging(string value);
    partial void OnMarkupGroupChanged();
    partial void OnInventSiteIdChanging(string value);
    partial void OnInventSiteIdChanged();
    partial void OnInventLocationChanging(string value);
    partial void OnInventLocationChanged();
    partial void OnCustItemGroupIdChanging(string value);
    partial void OnCustItemGroupIdChanged();
    partial void OnCommissionGroupChanging(string value);
    partial void OnCommissionGroupChanged();
    partial void OnSalesGroupChanging(string value);
    partial void OnSalesGroupChanged();
    partial void OnSalesPoolIdChanging(string value);
    partial void OnSalesPoolIdChanged();
    partial void OnMultiLineDiscChanging(string value);
    partial void OnMultiLineDiscChanged();
    partial void OnEndDiscChanging(string value);
    partial void OnEndDiscChanged();
    partial void OnPriceGroupChanging(string value);
    partial void OnPriceGroupChanged();
    partial void OnLineDiscChanging(string value);
    partial void OnLineDiscChanged();
    partial void OnPaymTermIdChanging(string value);
    partial void OnPaymTermIdChanged();
    partial void OnPaymModeChanging(string value);
    partial void OnPaymModeChanged();
    partial void OnPaymSpecChanging(string value);
    partial void OnPaymSpecChanged();
    partial void OnPaymSchedChanging(string value);
    partial void OnPaymSchedChanged();
    partial void OnPaymDayIdChanging(string value);
    partial void OnPaymDayIdChanged();
    partial void OnCashDiscChanging(string value);
    partial void OnCashDiscChanged();
    partial void OnBankAccountChanging(string value);
    partial void OnBankAccountChanged();
    partial void OnFineCode_BRChanging(string value);
    partial void OnFineCode_BRChanged();
    partial void OnInterestCode_BRChanging(string value);
    partial void OnInterestCode_BRChanged();
    partial void OnInvoiceAccountChanging(string value);
    partial void OnInvoiceAccountChanged();
    partial void OnInvoiceAddressChanging(string value);
    partial void OnInvoiceAddressChanged();
    partial void OnnumberSequenceGroupChanging(string value);
    partial void OnnumberSequenceGroupChanged();
    partial void OnTaxWithholdCalculate_THChanging(string value);
    partial void OnTaxWithholdCalculate_THChanged();
    partial void OnTaxWithholdGroup_THChanging(string value);
    partial void OnTaxWithholdGroup_THChanged();
    partial void OnDlvTermChanging(string value);
    partial void OnDlvTermChanged();
    partial void OnDlvModeChanging(string value);
    partial void OnDlvModeChanged();
    partial void OnDlvReasonChanging(string value);
    partial void OnDlvReasonChanged();
    partial void OnDestinationCodeIdChanging(string value);
    partial void OnDestinationCodeIdChanged();
    partial void OnVATNumChanging(string value);
    partial void OnVATNumChanged();
    partial void OnInclTaxChanging(string value);
    partial void OnInclTaxChanged();
    partial void OnCustFinalUser_BRChanging(string value);
    partial void OnCustFinalUser_BRChanged();
    partial void OnICMSContributor_BRChanging(string value);
    partial void OnICMSContributor_BRChanged();
    partial void OnServiceCodeOnDlvAddress_BRChanging(string value);
    partial void OnServiceCodeOnDlvAddress_BRChanged();
    partial void OnCCMNum_BRChanging(string value);
    partial void OnCCMNum_BRChanged();
    partial void OnCNAE_BRChanging(string value);
    partial void OnCNAE_BRChanged();
    partial void OnSuframa_BRChanging(string value);
    partial void OnSuframa_BRChanged();
    partial void OnSuframaNumber_BRChanging(string value);
    partial void OnSuframaNumber_BRChanged();
    partial void OnSuframaPISCOFINS_BRChanging(string value);
    partial void OnSuframaPISCOFINS_BRChanged();
    partial void OnGenerateIncomingFiscalDocument_BRChanging(string value);
    partial void OnGenerateIncomingFiscalDocument_BRChanged();
    partial void OnMainContactWorkerPartyNameChanging(string value);
    partial void OnMainContactWorkerPartyNameChanged();
    partial void OnMainContactWorkerPartyNumberChanging(string value);
    partial void OnMainContactWorkerPartyNumberChanged();
    partial void OnMainContactWorkerPersonnelNumberChanging(string value);
    partial void OnMainContactWorkerPersonnelNumberChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnPhoneNameChanging(string value);
    partial void OnPhoneNameChanged();
    partial void OnDefaultDimensionStrChanging(string value);
    partial void OnDefaultDimensionStrChanged();
    partial void OnTaxWithholdCalculate_INChanging(string value);
    partial void OnTaxWithholdCalculate_INChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmailNameChanging(string value);
    partial void OnEmailNameChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnUrlNameChanging(string value);
    partial void OnUrlNameChanged();
    #endregion
		
		public stg_Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroIDMig", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegistroIDMig
		{
			get
			{
				return this._RegistroIDMig;
			}
			set
			{
				if ((this._RegistroIDMig != value))
				{
					this.OnRegistroIDMigChanging(value);
					this.SendPropertyChanging();
					this._RegistroIDMig = value;
					this.SendPropertyChanged("RegistroIDMig");
					this.OnRegistroIDMigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNum", DbType="NVarChar(255)")]
		public string AccountNum
		{
			get
			{
				return this._AccountNum;
			}
			set
			{
				if ((this._AccountNum != value))
				{
					this.OnAccountNumChanging(value);
					this.SendPropertyChanging();
					this._AccountNum = value;
					this.SendPropertyChanged("AccountNum");
					this.OnAccountNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldAccountNum", DbType="NVarChar(255)")]
		public string OldAccountNum
		{
			get
			{
				return this._OldAccountNum;
			}
			set
			{
				if ((this._OldAccountNum != value))
				{
					this.OnOldAccountNumChanging(value);
					this.SendPropertyChanging();
					this._OldAccountNum = value;
					this.SendPropertyChanged("OldAccountNum");
					this.OnOldAccountNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustGroup", DbType="NVarChar(255)")]
		public string CustGroup
		{
			get
			{
				return this._CustGroup;
			}
			set
			{
				if ((this._CustGroup != value))
				{
					this.OnCustGroupChanging(value);
					this.SendPropertyChanging();
					this._CustGroup = value;
					this.SendPropertyChanged("CustGroup");
					this.OnCustGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="NVarChar(255)")]
		public string LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this.OnLanguageIdChanging(value);
					this.SendPropertyChanging();
					this._LanguageId = value;
					this.SendPropertyChanged("LanguageId");
					this.OnLanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="NVarChar(255)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustClassificationId", DbType="NVarChar(255)")]
		public string CustClassificationId
		{
			get
			{
				return this._CustClassificationId;
			}
			set
			{
				if ((this._CustClassificationId != value))
				{
					this.OnCustClassificationIdChanging(value);
					this.SendPropertyChanging();
					this._CustClassificationId = value;
					this.SendPropertyChanged("CustClassificationId");
					this.OnCustClassificationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyType", DbType="NVarChar(255)")]
		public string PartyType
		{
			get
			{
				return this._PartyType;
			}
			set
			{
				if ((this._PartyType != value))
				{
					this.OnPartyTypeChanging(value);
					this.SendPropertyChanging();
					this._PartyType = value;
					this.SendPropertyChanged("PartyType");
					this.OnPartyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(255)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(255)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(255)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAlias", DbType="NVarChar(255)")]
		public string NameAlias
		{
			get
			{
				return this._NameAlias;
			}
			set
			{
				if ((this._NameAlias != value))
				{
					this.OnNameAliasChanging(value);
					this.SendPropertyChanging();
					this._NameAlias = value;
					this.SendPropertyChanged("NameAlias");
					this.OnNameAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationRole", DbType="NVarChar(255)")]
		public string LocationRole
		{
			get
			{
				return this._LocationRole;
			}
			set
			{
				if ((this._LocationRole != value))
				{
					this.OnLocationRoleChanging(value);
					this.SendPropertyChanging();
					this._LocationRole = value;
					this.SendPropertyChanged("LocationRole");
					this.OnLocationRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(255)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(255)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNumber", DbType="NVarChar(255)")]
		public string StreetNumber
		{
			get
			{
				return this._StreetNumber;
			}
			set
			{
				if ((this._StreetNumber != value))
				{
					this.OnStreetNumberChanging(value);
					this.SendPropertyChanging();
					this._StreetNumber = value;
					this.SendPropertyChanged("StreetNumber");
					this.OnStreetNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingCompliment", DbType="NVarChar(255)")]
		public string BuildingCompliment
		{
			get
			{
				return this._BuildingCompliment;
			}
			set
			{
				if ((this._BuildingCompliment != value))
				{
					this.OnBuildingComplimentChanging(value);
					this.SendPropertyChanging();
					this._BuildingCompliment = value;
					this.SendPropertyChanged("BuildingCompliment");
					this.OnBuildingComplimentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBox", DbType="NVarChar(255)")]
		public string PostBox
		{
			get
			{
				return this._PostBox;
			}
			set
			{
				if ((this._PostBox != value))
				{
					this.OnPostBoxChanging(value);
					this.SendPropertyChanging();
					this._PostBox = value;
					this.SendPropertyChanged("PostBox");
					this.OnPostBoxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="NVarChar(255)")]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryRegionId", DbType="NVarChar(255)")]
		public string CountryRegionId
		{
			get
			{
				return this._CountryRegionId;
			}
			set
			{
				if ((this._CountryRegionId != value))
				{
					this.OnCountryRegionIdChanging(value);
					this.SendPropertyChanging();
					this._CountryRegionId = value;
					this.SendPropertyChanged("CountryRegionId");
					this.OnCountryRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxGroup", DbType="NVarChar(255)")]
		public string TaxGroup
		{
			get
			{
				return this._TaxGroup;
			}
			set
			{
				if ((this._TaxGroup != value))
				{
					this.OnTaxGroupChanging(value);
					this.SendPropertyChanging();
					this._TaxGroup = value;
					this.SendPropertyChanged("TaxGroup");
					this.OnTaxGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJCPFNum_BR", DbType="NVarChar(255)")]
		public string CNPJCPFNum_BR
		{
			get
			{
				return this._CNPJCPFNum_BR;
			}
			set
			{
				if ((this._CNPJCPFNum_BR != value))
				{
					this.OnCNPJCPFNum_BRChanging(value);
					this.SendPropertyChanging();
					this._CNPJCPFNum_BR = value;
					this.SendPropertyChanged("CNPJCPFNum_BR");
					this.OnCNPJCPFNum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IENum_BR", DbType="NVarChar(255)")]
		public string IENum_BR
		{
			get
			{
				return this._IENum_BR;
			}
			set
			{
				if ((this._IENum_BR != value))
				{
					this.OnIENum_BRChanging(value);
					this.SendPropertyChanging();
					this._IENum_BR = value;
					this.SendPropertyChanged("IENum_BR");
					this.OnIENum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatisticsGroup", DbType="NVarChar(255)")]
		public string StatisticsGroup
		{
			get
			{
				return this._StatisticsGroup;
			}
			set
			{
				if ((this._StatisticsGroup != value))
				{
					this.OnStatisticsGroupChanging(value);
					this.SendPropertyChanging();
					this._StatisticsGroup = value;
					this.SendPropertyChanged("StatisticsGroup");
					this.OnStatisticsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPersonId", DbType="NVarChar(255)")]
		public string ContactPersonId
		{
			get
			{
				return this._ContactPersonId;
			}
			set
			{
				if ((this._ContactPersonId != value))
				{
					this.OnContactPersonIdChanging(value);
					this.SendPropertyChanging();
					this._ContactPersonId = value;
					this.SendPropertyChanged("ContactPersonId");
					this.OnContactPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineOfBusinessId", DbType="NVarChar(255)")]
		public string LineOfBusinessId
		{
			get
			{
				return this._LineOfBusinessId;
			}
			set
			{
				if ((this._LineOfBusinessId != value))
				{
					this.OnLineOfBusinessIdChanging(value);
					this.SendPropertyChanging();
					this._LineOfBusinessId = value;
					this.SendPropertyChanged("LineOfBusinessId");
					this.OnLineOfBusinessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegmentId", DbType="NVarChar(255)")]
		public string SegmentId
		{
			get
			{
				return this._SegmentId;
			}
			set
			{
				if ((this._SegmentId != value))
				{
					this.OnSegmentIdChanging(value);
					this.SendPropertyChanging();
					this._SegmentId = value;
					this.SendPropertyChanged("SegmentId");
					this.OnSegmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubsegmentId", DbType="NVarChar(255)")]
		public string SubsegmentId
		{
			get
			{
				return this._SubsegmentId;
			}
			set
			{
				if ((this._SubsegmentId != value))
				{
					this.OnSubsegmentIdChanging(value);
					this.SendPropertyChanging();
					this._SubsegmentId = value;
					this.SendPropertyChanged("SubsegmentId");
					this.OnSubsegmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyChainId", DbType="NVarChar(255)")]
		public string CompanyChainId
		{
			get
			{
				return this._CompanyChainId;
			}
			set
			{
				if ((this._CompanyChainId != value))
				{
					this.OnCompanyChainIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyChainId = value;
					this.SendPropertyChanged("CompanyChainId");
					this.OnCompanyChainIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrictId", DbType="NVarChar(255)")]
		public string SalesDistrictId
		{
			get
			{
				return this._SalesDistrictId;
			}
			set
			{
				if ((this._SalesDistrictId != value))
				{
					this.OnSalesDistrictIdChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrictId = value;
					this.SendPropertyChanged("SalesDistrictId");
					this.OnSalesDistrictIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blocked", DbType="NVarChar(255)")]
		public string Blocked
		{
			get
			{
				return this._Blocked;
			}
			set
			{
				if ((this._Blocked != value))
				{
					this.OnBlockedChanging(value);
					this.SendPropertyChanging();
					this._Blocked = value;
					this.SendPropertyChanged("Blocked");
					this.OnBlockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MandatoryCreditLimit", DbType="NVarChar(255)")]
		public string MandatoryCreditLimit
		{
			get
			{
				return this._MandatoryCreditLimit;
			}
			set
			{
				if ((this._MandatoryCreditLimit != value))
				{
					this.OnMandatoryCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._MandatoryCreditLimit = value;
					this.SendPropertyChanged("MandatoryCreditLimit");
					this.OnMandatoryCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditRating", DbType="NVarChar(255)")]
		public string CreditRating
		{
			get
			{
				return this._CreditRating;
			}
			set
			{
				if ((this._CreditRating != value))
				{
					this.OnCreditRatingChanging(value);
					this.SendPropertyChanging();
					this._CreditRating = value;
					this.SendPropertyChanged("CreditRating");
					this.OnCreditRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditMax", DbType="NVarChar(255)")]
		public string CreditMax
		{
			get
			{
				return this._CreditMax;
			}
			set
			{
				if ((this._CreditMax != value))
				{
					this.OnCreditMaxChanging(value);
					this.SendPropertyChanging();
					this._CreditMax = value;
					this.SendPropertyChanged("CreditMax");
					this.OnCreditMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkupGroup", DbType="NVarChar(255)")]
		public string MarkupGroup
		{
			get
			{
				return this._MarkupGroup;
			}
			set
			{
				if ((this._MarkupGroup != value))
				{
					this.OnMarkupGroupChanging(value);
					this.SendPropertyChanging();
					this._MarkupGroup = value;
					this.SendPropertyChanged("MarkupGroup");
					this.OnMarkupGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventSiteId", DbType="NVarChar(255)")]
		public string InventSiteId
		{
			get
			{
				return this._InventSiteId;
			}
			set
			{
				if ((this._InventSiteId != value))
				{
					this.OnInventSiteIdChanging(value);
					this.SendPropertyChanging();
					this._InventSiteId = value;
					this.SendPropertyChanged("InventSiteId");
					this.OnInventSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventLocation", DbType="NVarChar(255)")]
		public string InventLocation
		{
			get
			{
				return this._InventLocation;
			}
			set
			{
				if ((this._InventLocation != value))
				{
					this.OnInventLocationChanging(value);
					this.SendPropertyChanging();
					this._InventLocation = value;
					this.SendPropertyChanged("InventLocation");
					this.OnInventLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustItemGroupId", DbType="NVarChar(255)")]
		public string CustItemGroupId
		{
			get
			{
				return this._CustItemGroupId;
			}
			set
			{
				if ((this._CustItemGroupId != value))
				{
					this.OnCustItemGroupIdChanging(value);
					this.SendPropertyChanging();
					this._CustItemGroupId = value;
					this.SendPropertyChanged("CustItemGroupId");
					this.OnCustItemGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommissionGroup", DbType="NVarChar(255)")]
		public string CommissionGroup
		{
			get
			{
				return this._CommissionGroup;
			}
			set
			{
				if ((this._CommissionGroup != value))
				{
					this.OnCommissionGroupChanging(value);
					this.SendPropertyChanging();
					this._CommissionGroup = value;
					this.SendPropertyChanged("CommissionGroup");
					this.OnCommissionGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesGroup", DbType="NVarChar(255)")]
		public string SalesGroup
		{
			get
			{
				return this._SalesGroup;
			}
			set
			{
				if ((this._SalesGroup != value))
				{
					this.OnSalesGroupChanging(value);
					this.SendPropertyChanging();
					this._SalesGroup = value;
					this.SendPropertyChanged("SalesGroup");
					this.OnSalesGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPoolId", DbType="NVarChar(255)")]
		public string SalesPoolId
		{
			get
			{
				return this._SalesPoolId;
			}
			set
			{
				if ((this._SalesPoolId != value))
				{
					this.OnSalesPoolIdChanging(value);
					this.SendPropertyChanging();
					this._SalesPoolId = value;
					this.SendPropertyChanged("SalesPoolId");
					this.OnSalesPoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MultiLineDisc", DbType="NVarChar(255)")]
		public string MultiLineDisc
		{
			get
			{
				return this._MultiLineDisc;
			}
			set
			{
				if ((this._MultiLineDisc != value))
				{
					this.OnMultiLineDiscChanging(value);
					this.SendPropertyChanging();
					this._MultiLineDisc = value;
					this.SendPropertyChanged("MultiLineDisc");
					this.OnMultiLineDiscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDisc", DbType="NVarChar(255)")]
		public string EndDisc
		{
			get
			{
				return this._EndDisc;
			}
			set
			{
				if ((this._EndDisc != value))
				{
					this.OnEndDiscChanging(value);
					this.SendPropertyChanging();
					this._EndDisc = value;
					this.SendPropertyChanged("EndDisc");
					this.OnEndDiscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceGroup", DbType="NVarChar(255)")]
		public string PriceGroup
		{
			get
			{
				return this._PriceGroup;
			}
			set
			{
				if ((this._PriceGroup != value))
				{
					this.OnPriceGroupChanging(value);
					this.SendPropertyChanging();
					this._PriceGroup = value;
					this.SendPropertyChanged("PriceGroup");
					this.OnPriceGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineDisc", DbType="NVarChar(255)")]
		public string LineDisc
		{
			get
			{
				return this._LineDisc;
			}
			set
			{
				if ((this._LineDisc != value))
				{
					this.OnLineDiscChanging(value);
					this.SendPropertyChanging();
					this._LineDisc = value;
					this.SendPropertyChanged("LineDisc");
					this.OnLineDiscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymTermId", DbType="NVarChar(255)")]
		public string PaymTermId
		{
			get
			{
				return this._PaymTermId;
			}
			set
			{
				if ((this._PaymTermId != value))
				{
					this.OnPaymTermIdChanging(value);
					this.SendPropertyChanging();
					this._PaymTermId = value;
					this.SendPropertyChanged("PaymTermId");
					this.OnPaymTermIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymMode", DbType="NVarChar(255)")]
		public string PaymMode
		{
			get
			{
				return this._PaymMode;
			}
			set
			{
				if ((this._PaymMode != value))
				{
					this.OnPaymModeChanging(value);
					this.SendPropertyChanging();
					this._PaymMode = value;
					this.SendPropertyChanged("PaymMode");
					this.OnPaymModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymSpec", DbType="NVarChar(255)")]
		public string PaymSpec
		{
			get
			{
				return this._PaymSpec;
			}
			set
			{
				if ((this._PaymSpec != value))
				{
					this.OnPaymSpecChanging(value);
					this.SendPropertyChanging();
					this._PaymSpec = value;
					this.SendPropertyChanged("PaymSpec");
					this.OnPaymSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymSched", DbType="NVarChar(255)")]
		public string PaymSched
		{
			get
			{
				return this._PaymSched;
			}
			set
			{
				if ((this._PaymSched != value))
				{
					this.OnPaymSchedChanging(value);
					this.SendPropertyChanging();
					this._PaymSched = value;
					this.SendPropertyChanged("PaymSched");
					this.OnPaymSchedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymDayId", DbType="NVarChar(255)")]
		public string PaymDayId
		{
			get
			{
				return this._PaymDayId;
			}
			set
			{
				if ((this._PaymDayId != value))
				{
					this.OnPaymDayIdChanging(value);
					this.SendPropertyChanging();
					this._PaymDayId = value;
					this.SendPropertyChanged("PaymDayId");
					this.OnPaymDayIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashDisc", DbType="NVarChar(255)")]
		public string CashDisc
		{
			get
			{
				return this._CashDisc;
			}
			set
			{
				if ((this._CashDisc != value))
				{
					this.OnCashDiscChanging(value);
					this.SendPropertyChanging();
					this._CashDisc = value;
					this.SendPropertyChanged("CashDisc");
					this.OnCashDiscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccount", DbType="NVarChar(255)")]
		public string BankAccount
		{
			get
			{
				return this._BankAccount;
			}
			set
			{
				if ((this._BankAccount != value))
				{
					this.OnBankAccountChanging(value);
					this.SendPropertyChanging();
					this._BankAccount = value;
					this.SendPropertyChanged("BankAccount");
					this.OnBankAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FineCode_BR", DbType="NVarChar(255)")]
		public string FineCode_BR
		{
			get
			{
				return this._FineCode_BR;
			}
			set
			{
				if ((this._FineCode_BR != value))
				{
					this.OnFineCode_BRChanging(value);
					this.SendPropertyChanging();
					this._FineCode_BR = value;
					this.SendPropertyChanged("FineCode_BR");
					this.OnFineCode_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterestCode_BR", DbType="NVarChar(255)")]
		public string InterestCode_BR
		{
			get
			{
				return this._InterestCode_BR;
			}
			set
			{
				if ((this._InterestCode_BR != value))
				{
					this.OnInterestCode_BRChanging(value);
					this.SendPropertyChanging();
					this._InterestCode_BR = value;
					this.SendPropertyChanged("InterestCode_BR");
					this.OnInterestCode_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAccount", DbType="NVarChar(255)")]
		public string InvoiceAccount
		{
			get
			{
				return this._InvoiceAccount;
			}
			set
			{
				if ((this._InvoiceAccount != value))
				{
					this.OnInvoiceAccountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceAccount = value;
					this.SendPropertyChanged("InvoiceAccount");
					this.OnInvoiceAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAddress", DbType="NVarChar(255)")]
		public string InvoiceAddress
		{
			get
			{
				return this._InvoiceAddress;
			}
			set
			{
				if ((this._InvoiceAddress != value))
				{
					this.OnInvoiceAddressChanging(value);
					this.SendPropertyChanging();
					this._InvoiceAddress = value;
					this.SendPropertyChanged("InvoiceAddress");
					this.OnInvoiceAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberSequenceGroup", DbType="NVarChar(255)")]
		public string numberSequenceGroup
		{
			get
			{
				return this._numberSequenceGroup;
			}
			set
			{
				if ((this._numberSequenceGroup != value))
				{
					this.OnnumberSequenceGroupChanging(value);
					this.SendPropertyChanging();
					this._numberSequenceGroup = value;
					this.SendPropertyChanged("numberSequenceGroup");
					this.OnnumberSequenceGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxWithholdCalculate_TH", DbType="NVarChar(255)")]
		public string TaxWithholdCalculate_TH
		{
			get
			{
				return this._TaxWithholdCalculate_TH;
			}
			set
			{
				if ((this._TaxWithholdCalculate_TH != value))
				{
					this.OnTaxWithholdCalculate_THChanging(value);
					this.SendPropertyChanging();
					this._TaxWithholdCalculate_TH = value;
					this.SendPropertyChanged("TaxWithholdCalculate_TH");
					this.OnTaxWithholdCalculate_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxWithholdGroup_TH", DbType="NVarChar(255)")]
		public string TaxWithholdGroup_TH
		{
			get
			{
				return this._TaxWithholdGroup_TH;
			}
			set
			{
				if ((this._TaxWithholdGroup_TH != value))
				{
					this.OnTaxWithholdGroup_THChanging(value);
					this.SendPropertyChanging();
					this._TaxWithholdGroup_TH = value;
					this.SendPropertyChanged("TaxWithholdGroup_TH");
					this.OnTaxWithholdGroup_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DlvTerm", DbType="NVarChar(255)")]
		public string DlvTerm
		{
			get
			{
				return this._DlvTerm;
			}
			set
			{
				if ((this._DlvTerm != value))
				{
					this.OnDlvTermChanging(value);
					this.SendPropertyChanging();
					this._DlvTerm = value;
					this.SendPropertyChanged("DlvTerm");
					this.OnDlvTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DlvMode", DbType="NVarChar(255)")]
		public string DlvMode
		{
			get
			{
				return this._DlvMode;
			}
			set
			{
				if ((this._DlvMode != value))
				{
					this.OnDlvModeChanging(value);
					this.SendPropertyChanging();
					this._DlvMode = value;
					this.SendPropertyChanged("DlvMode");
					this.OnDlvModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DlvReason", DbType="NVarChar(255)")]
		public string DlvReason
		{
			get
			{
				return this._DlvReason;
			}
			set
			{
				if ((this._DlvReason != value))
				{
					this.OnDlvReasonChanging(value);
					this.SendPropertyChanging();
					this._DlvReason = value;
					this.SendPropertyChanged("DlvReason");
					this.OnDlvReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationCodeId", DbType="NVarChar(255)")]
		public string DestinationCodeId
		{
			get
			{
				return this._DestinationCodeId;
			}
			set
			{
				if ((this._DestinationCodeId != value))
				{
					this.OnDestinationCodeIdChanging(value);
					this.SendPropertyChanging();
					this._DestinationCodeId = value;
					this.SendPropertyChanged("DestinationCodeId");
					this.OnDestinationCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATNum", DbType="NVarChar(255)")]
		public string VATNum
		{
			get
			{
				return this._VATNum;
			}
			set
			{
				if ((this._VATNum != value))
				{
					this.OnVATNumChanging(value);
					this.SendPropertyChanging();
					this._VATNum = value;
					this.SendPropertyChanged("VATNum");
					this.OnVATNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InclTax", DbType="NVarChar(255)")]
		public string InclTax
		{
			get
			{
				return this._InclTax;
			}
			set
			{
				if ((this._InclTax != value))
				{
					this.OnInclTaxChanging(value);
					this.SendPropertyChanging();
					this._InclTax = value;
					this.SendPropertyChanged("InclTax");
					this.OnInclTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustFinalUser_BR", DbType="NVarChar(255)")]
		public string CustFinalUser_BR
		{
			get
			{
				return this._CustFinalUser_BR;
			}
			set
			{
				if ((this._CustFinalUser_BR != value))
				{
					this.OnCustFinalUser_BRChanging(value);
					this.SendPropertyChanging();
					this._CustFinalUser_BR = value;
					this.SendPropertyChanged("CustFinalUser_BR");
					this.OnCustFinalUser_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICMSContributor_BR", DbType="NVarChar(255)")]
		public string ICMSContributor_BR
		{
			get
			{
				return this._ICMSContributor_BR;
			}
			set
			{
				if ((this._ICMSContributor_BR != value))
				{
					this.OnICMSContributor_BRChanging(value);
					this.SendPropertyChanging();
					this._ICMSContributor_BR = value;
					this.SendPropertyChanged("ICMSContributor_BR");
					this.OnICMSContributor_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCodeOnDlvAddress_BR", DbType="NVarChar(255)")]
		public string ServiceCodeOnDlvAddress_BR
		{
			get
			{
				return this._ServiceCodeOnDlvAddress_BR;
			}
			set
			{
				if ((this._ServiceCodeOnDlvAddress_BR != value))
				{
					this.OnServiceCodeOnDlvAddress_BRChanging(value);
					this.SendPropertyChanging();
					this._ServiceCodeOnDlvAddress_BR = value;
					this.SendPropertyChanged("ServiceCodeOnDlvAddress_BR");
					this.OnServiceCodeOnDlvAddress_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCMNum_BR", DbType="NVarChar(255)")]
		public string CCMNum_BR
		{
			get
			{
				return this._CCMNum_BR;
			}
			set
			{
				if ((this._CCMNum_BR != value))
				{
					this.OnCCMNum_BRChanging(value);
					this.SendPropertyChanging();
					this._CCMNum_BR = value;
					this.SendPropertyChanged("CCMNum_BR");
					this.OnCCMNum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNAE_BR", DbType="NVarChar(255)")]
		public string CNAE_BR
		{
			get
			{
				return this._CNAE_BR;
			}
			set
			{
				if ((this._CNAE_BR != value))
				{
					this.OnCNAE_BRChanging(value);
					this.SendPropertyChanging();
					this._CNAE_BR = value;
					this.SendPropertyChanged("CNAE_BR");
					this.OnCNAE_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suframa_BR", DbType="NVarChar(255)")]
		public string Suframa_BR
		{
			get
			{
				return this._Suframa_BR;
			}
			set
			{
				if ((this._Suframa_BR != value))
				{
					this.OnSuframa_BRChanging(value);
					this.SendPropertyChanging();
					this._Suframa_BR = value;
					this.SendPropertyChanged("Suframa_BR");
					this.OnSuframa_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuframaNumber_BR", DbType="NVarChar(255)")]
		public string SuframaNumber_BR
		{
			get
			{
				return this._SuframaNumber_BR;
			}
			set
			{
				if ((this._SuframaNumber_BR != value))
				{
					this.OnSuframaNumber_BRChanging(value);
					this.SendPropertyChanging();
					this._SuframaNumber_BR = value;
					this.SendPropertyChanged("SuframaNumber_BR");
					this.OnSuframaNumber_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuframaPISCOFINS_BR", DbType="NVarChar(255)")]
		public string SuframaPISCOFINS_BR
		{
			get
			{
				return this._SuframaPISCOFINS_BR;
			}
			set
			{
				if ((this._SuframaPISCOFINS_BR != value))
				{
					this.OnSuframaPISCOFINS_BRChanging(value);
					this.SendPropertyChanging();
					this._SuframaPISCOFINS_BR = value;
					this.SendPropertyChanged("SuframaPISCOFINS_BR");
					this.OnSuframaPISCOFINS_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenerateIncomingFiscalDocument_BR", DbType="NVarChar(255)")]
		public string GenerateIncomingFiscalDocument_BR
		{
			get
			{
				return this._GenerateIncomingFiscalDocument_BR;
			}
			set
			{
				if ((this._GenerateIncomingFiscalDocument_BR != value))
				{
					this.OnGenerateIncomingFiscalDocument_BRChanging(value);
					this.SendPropertyChanging();
					this._GenerateIncomingFiscalDocument_BR = value;
					this.SendPropertyChanged("GenerateIncomingFiscalDocument_BR");
					this.OnGenerateIncomingFiscalDocument_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainContactWorkerPartyName", DbType="NVarChar(255)")]
		public string MainContactWorkerPartyName
		{
			get
			{
				return this._MainContactWorkerPartyName;
			}
			set
			{
				if ((this._MainContactWorkerPartyName != value))
				{
					this.OnMainContactWorkerPartyNameChanging(value);
					this.SendPropertyChanging();
					this._MainContactWorkerPartyName = value;
					this.SendPropertyChanged("MainContactWorkerPartyName");
					this.OnMainContactWorkerPartyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainContactWorkerPartyNumber", DbType="NVarChar(255)")]
		public string MainContactWorkerPartyNumber
		{
			get
			{
				return this._MainContactWorkerPartyNumber;
			}
			set
			{
				if ((this._MainContactWorkerPartyNumber != value))
				{
					this.OnMainContactWorkerPartyNumberChanging(value);
					this.SendPropertyChanging();
					this._MainContactWorkerPartyNumber = value;
					this.SendPropertyChanged("MainContactWorkerPartyNumber");
					this.OnMainContactWorkerPartyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainContactWorkerPersonnelNumber", DbType="NVarChar(255)")]
		public string MainContactWorkerPersonnelNumber
		{
			get
			{
				return this._MainContactWorkerPersonnelNumber;
			}
			set
			{
				if ((this._MainContactWorkerPersonnelNumber != value))
				{
					this.OnMainContactWorkerPersonnelNumberChanging(value);
					this.SendPropertyChanging();
					this._MainContactWorkerPersonnelNumber = value;
					this.SendPropertyChanged("MainContactWorkerPersonnelNumber");
					this.OnMainContactWorkerPersonnelNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneName", DbType="NVarChar(255)")]
		public string PhoneName
		{
			get
			{
				return this._PhoneName;
			}
			set
			{
				if ((this._PhoneName != value))
				{
					this.OnPhoneNameChanging(value);
					this.SendPropertyChanging();
					this._PhoneName = value;
					this.SendPropertyChanged("PhoneName");
					this.OnPhoneNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultDimensionStr", DbType="NVarChar(255)")]
		public string DefaultDimensionStr
		{
			get
			{
				return this._DefaultDimensionStr;
			}
			set
			{
				if ((this._DefaultDimensionStr != value))
				{
					this.OnDefaultDimensionStrChanging(value);
					this.SendPropertyChanging();
					this._DefaultDimensionStr = value;
					this.SendPropertyChanged("DefaultDimensionStr");
					this.OnDefaultDimensionStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxWithholdCalculate_IN", DbType="NVarChar(255)")]
		public string TaxWithholdCalculate_IN
		{
			get
			{
				return this._TaxWithholdCalculate_IN;
			}
			set
			{
				if ((this._TaxWithholdCalculate_IN != value))
				{
					this.OnTaxWithholdCalculate_INChanging(value);
					this.SendPropertyChanging();
					this._TaxWithholdCalculate_IN = value;
					this.SendPropertyChanged("TaxWithholdCalculate_IN");
					this.OnTaxWithholdCalculate_INChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailName", DbType="NVarChar(255)")]
		public string EmailName
		{
			get
			{
				return this._EmailName;
			}
			set
			{
				if ((this._EmailName != value))
				{
					this.OnEmailNameChanging(value);
					this.SendPropertyChanging();
					this._EmailName = value;
					this.SendPropertyChanged("EmailName");
					this.OnEmailNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlName", DbType="NVarChar(255)")]
		public string UrlName
		{
			get
			{
				return this._UrlName;
			}
			set
			{
				if ((this._UrlName != value))
				{
					this.OnUrlNameChanging(value);
					this.SendPropertyChanging();
					this._UrlName = value;
					this.SendPropertyChanged("UrlName");
					this.OnUrlNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stg_Fornecedores")]
	public partial class stg_Fornecedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegistroIDMig;
		
		private string _AccountNum;
		
		private string _OldAccountNum;
		
		private string _Name;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _CountryRegionId;
		
		private string _NameAlias;
		
		private string _VendGroup;
		
		private string _PartyType;
		
		private string _Currency;
		
		private string _LanguageId;
		
		private string _LocationRole;
		
		private string _ZipCode;
		
		private string _Street;
		
		private string _StreetNumber;
		
		private string _BuildingCompliment;
		
		private string _PostBox;
		
		private string _City;
		
		private string _DistrictName;
		
		private string _State;
		
		private string _BankAccount;
		
		private string _ItemBuyerGroupId;
		
		private string _CompanyChainId;
		
		private string _TaxGroup;
		
		private string _DlvMode;
		
		private string _PurchPoolId;
		
		private string _PaymTermId;
		
		private string _PaymMode;
		
		private string _CNPJCPFNum_BR;
		
		private string _IENum_BR;
		
		private string _CCMNum_BR;
		
		private string _Phone;
		
		private string _PhoneName;
		
		private string _Email;
		
		private string _EmailName;
		
		private string _URL;
		
		private string _UrlName;
		
		private string _TaxWithholdGroup;
		
		private string _TaxWithholdCalculate;
		
		private string _InclTax;
		
		private string _InventSiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistroIDMigChanging(int value);
    partial void OnRegistroIDMigChanged();
    partial void OnAccountNumChanging(string value);
    partial void OnAccountNumChanged();
    partial void OnOldAccountNumChanging(string value);
    partial void OnOldAccountNumChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnCountryRegionIdChanging(string value);
    partial void OnCountryRegionIdChanged();
    partial void OnNameAliasChanging(string value);
    partial void OnNameAliasChanged();
    partial void OnVendGroupChanging(string value);
    partial void OnVendGroupChanged();
    partial void OnPartyTypeChanging(string value);
    partial void OnPartyTypeChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnLanguageIdChanging(string value);
    partial void OnLanguageIdChanged();
    partial void OnLocationRoleChanging(string value);
    partial void OnLocationRoleChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnStreetNumberChanging(string value);
    partial void OnStreetNumberChanged();
    partial void OnBuildingComplimentChanging(string value);
    partial void OnBuildingComplimentChanged();
    partial void OnPostBoxChanging(string value);
    partial void OnPostBoxChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnBankAccountChanging(string value);
    partial void OnBankAccountChanged();
    partial void OnItemBuyerGroupIdChanging(string value);
    partial void OnItemBuyerGroupIdChanged();
    partial void OnCompanyChainIdChanging(string value);
    partial void OnCompanyChainIdChanged();
    partial void OnTaxGroupChanging(string value);
    partial void OnTaxGroupChanged();
    partial void OnDlvModeChanging(string value);
    partial void OnDlvModeChanged();
    partial void OnPurchPoolIdChanging(string value);
    partial void OnPurchPoolIdChanged();
    partial void OnPaymTermIdChanging(string value);
    partial void OnPaymTermIdChanged();
    partial void OnPaymModeChanging(string value);
    partial void OnPaymModeChanged();
    partial void OnCNPJCPFNum_BRChanging(string value);
    partial void OnCNPJCPFNum_BRChanged();
    partial void OnIENum_BRChanging(string value);
    partial void OnIENum_BRChanged();
    partial void OnCCMNum_BRChanging(string value);
    partial void OnCCMNum_BRChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnPhoneNameChanging(string value);
    partial void OnPhoneNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmailNameChanging(string value);
    partial void OnEmailNameChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnUrlNameChanging(string value);
    partial void OnUrlNameChanged();
    partial void OnTaxWithholdGroupChanging(string value);
    partial void OnTaxWithholdGroupChanged();
    partial void OnTaxWithholdCalculateChanging(string value);
    partial void OnTaxWithholdCalculateChanged();
    partial void OnInclTaxChanging(string value);
    partial void OnInclTaxChanged();
    partial void OnInventSiteIdChanging(string value);
    partial void OnInventSiteIdChanged();
    #endregion
		
		public stg_Fornecedore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroIDMig", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegistroIDMig
		{
			get
			{
				return this._RegistroIDMig;
			}
			set
			{
				if ((this._RegistroIDMig != value))
				{
					this.OnRegistroIDMigChanging(value);
					this.SendPropertyChanging();
					this._RegistroIDMig = value;
					this.SendPropertyChanged("RegistroIDMig");
					this.OnRegistroIDMigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNum", DbType="NVarChar(255)")]
		public string AccountNum
		{
			get
			{
				return this._AccountNum;
			}
			set
			{
				if ((this._AccountNum != value))
				{
					this.OnAccountNumChanging(value);
					this.SendPropertyChanging();
					this._AccountNum = value;
					this.SendPropertyChanged("AccountNum");
					this.OnAccountNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldAccountNum", DbType="NVarChar(255)")]
		public string OldAccountNum
		{
			get
			{
				return this._OldAccountNum;
			}
			set
			{
				if ((this._OldAccountNum != value))
				{
					this.OnOldAccountNumChanging(value);
					this.SendPropertyChanging();
					this._OldAccountNum = value;
					this.SendPropertyChanged("OldAccountNum");
					this.OnOldAccountNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(255)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(255)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(255)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryRegionId", DbType="NVarChar(255)")]
		public string CountryRegionId
		{
			get
			{
				return this._CountryRegionId;
			}
			set
			{
				if ((this._CountryRegionId != value))
				{
					this.OnCountryRegionIdChanging(value);
					this.SendPropertyChanging();
					this._CountryRegionId = value;
					this.SendPropertyChanged("CountryRegionId");
					this.OnCountryRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAlias", DbType="NVarChar(255)")]
		public string NameAlias
		{
			get
			{
				return this._NameAlias;
			}
			set
			{
				if ((this._NameAlias != value))
				{
					this.OnNameAliasChanging(value);
					this.SendPropertyChanging();
					this._NameAlias = value;
					this.SendPropertyChanged("NameAlias");
					this.OnNameAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendGroup", DbType="NVarChar(255)")]
		public string VendGroup
		{
			get
			{
				return this._VendGroup;
			}
			set
			{
				if ((this._VendGroup != value))
				{
					this.OnVendGroupChanging(value);
					this.SendPropertyChanging();
					this._VendGroup = value;
					this.SendPropertyChanged("VendGroup");
					this.OnVendGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyType", DbType="NVarChar(255)")]
		public string PartyType
		{
			get
			{
				return this._PartyType;
			}
			set
			{
				if ((this._PartyType != value))
				{
					this.OnPartyTypeChanging(value);
					this.SendPropertyChanging();
					this._PartyType = value;
					this.SendPropertyChanged("PartyType");
					this.OnPartyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="NVarChar(255)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="NVarChar(255)")]
		public string LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this.OnLanguageIdChanging(value);
					this.SendPropertyChanging();
					this._LanguageId = value;
					this.SendPropertyChanged("LanguageId");
					this.OnLanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationRole", DbType="NVarChar(255)")]
		public string LocationRole
		{
			get
			{
				return this._LocationRole;
			}
			set
			{
				if ((this._LocationRole != value))
				{
					this.OnLocationRoleChanging(value);
					this.SendPropertyChanging();
					this._LocationRole = value;
					this.SendPropertyChanged("LocationRole");
					this.OnLocationRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(255)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(255)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNumber", DbType="NVarChar(255)")]
		public string StreetNumber
		{
			get
			{
				return this._StreetNumber;
			}
			set
			{
				if ((this._StreetNumber != value))
				{
					this.OnStreetNumberChanging(value);
					this.SendPropertyChanging();
					this._StreetNumber = value;
					this.SendPropertyChanged("StreetNumber");
					this.OnStreetNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingCompliment", DbType="NVarChar(255)")]
		public string BuildingCompliment
		{
			get
			{
				return this._BuildingCompliment;
			}
			set
			{
				if ((this._BuildingCompliment != value))
				{
					this.OnBuildingComplimentChanging(value);
					this.SendPropertyChanging();
					this._BuildingCompliment = value;
					this.SendPropertyChanged("BuildingCompliment");
					this.OnBuildingComplimentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostBox", DbType="NVarChar(255)")]
		public string PostBox
		{
			get
			{
				return this._PostBox;
			}
			set
			{
				if ((this._PostBox != value))
				{
					this.OnPostBoxChanging(value);
					this.SendPropertyChanging();
					this._PostBox = value;
					this.SendPropertyChanged("PostBox");
					this.OnPostBoxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="NVarChar(255)")]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccount", DbType="NVarChar(255)")]
		public string BankAccount
		{
			get
			{
				return this._BankAccount;
			}
			set
			{
				if ((this._BankAccount != value))
				{
					this.OnBankAccountChanging(value);
					this.SendPropertyChanging();
					this._BankAccount = value;
					this.SendPropertyChanged("BankAccount");
					this.OnBankAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemBuyerGroupId", DbType="NVarChar(255)")]
		public string ItemBuyerGroupId
		{
			get
			{
				return this._ItemBuyerGroupId;
			}
			set
			{
				if ((this._ItemBuyerGroupId != value))
				{
					this.OnItemBuyerGroupIdChanging(value);
					this.SendPropertyChanging();
					this._ItemBuyerGroupId = value;
					this.SendPropertyChanged("ItemBuyerGroupId");
					this.OnItemBuyerGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyChainId", DbType="NVarChar(255)")]
		public string CompanyChainId
		{
			get
			{
				return this._CompanyChainId;
			}
			set
			{
				if ((this._CompanyChainId != value))
				{
					this.OnCompanyChainIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyChainId = value;
					this.SendPropertyChanged("CompanyChainId");
					this.OnCompanyChainIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxGroup", DbType="NVarChar(255)")]
		public string TaxGroup
		{
			get
			{
				return this._TaxGroup;
			}
			set
			{
				if ((this._TaxGroup != value))
				{
					this.OnTaxGroupChanging(value);
					this.SendPropertyChanging();
					this._TaxGroup = value;
					this.SendPropertyChanged("TaxGroup");
					this.OnTaxGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DlvMode", DbType="NVarChar(255)")]
		public string DlvMode
		{
			get
			{
				return this._DlvMode;
			}
			set
			{
				if ((this._DlvMode != value))
				{
					this.OnDlvModeChanging(value);
					this.SendPropertyChanging();
					this._DlvMode = value;
					this.SendPropertyChanged("DlvMode");
					this.OnDlvModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchPoolId", DbType="NVarChar(255)")]
		public string PurchPoolId
		{
			get
			{
				return this._PurchPoolId;
			}
			set
			{
				if ((this._PurchPoolId != value))
				{
					this.OnPurchPoolIdChanging(value);
					this.SendPropertyChanging();
					this._PurchPoolId = value;
					this.SendPropertyChanged("PurchPoolId");
					this.OnPurchPoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymTermId", DbType="NVarChar(255)")]
		public string PaymTermId
		{
			get
			{
				return this._PaymTermId;
			}
			set
			{
				if ((this._PaymTermId != value))
				{
					this.OnPaymTermIdChanging(value);
					this.SendPropertyChanging();
					this._PaymTermId = value;
					this.SendPropertyChanged("PaymTermId");
					this.OnPaymTermIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymMode", DbType="NVarChar(255)")]
		public string PaymMode
		{
			get
			{
				return this._PaymMode;
			}
			set
			{
				if ((this._PaymMode != value))
				{
					this.OnPaymModeChanging(value);
					this.SendPropertyChanging();
					this._PaymMode = value;
					this.SendPropertyChanged("PaymMode");
					this.OnPaymModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJCPFNum_BR", DbType="NVarChar(255)")]
		public string CNPJCPFNum_BR
		{
			get
			{
				return this._CNPJCPFNum_BR;
			}
			set
			{
				if ((this._CNPJCPFNum_BR != value))
				{
					this.OnCNPJCPFNum_BRChanging(value);
					this.SendPropertyChanging();
					this._CNPJCPFNum_BR = value;
					this.SendPropertyChanged("CNPJCPFNum_BR");
					this.OnCNPJCPFNum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IENum_BR", DbType="NVarChar(255)")]
		public string IENum_BR
		{
			get
			{
				return this._IENum_BR;
			}
			set
			{
				if ((this._IENum_BR != value))
				{
					this.OnIENum_BRChanging(value);
					this.SendPropertyChanging();
					this._IENum_BR = value;
					this.SendPropertyChanged("IENum_BR");
					this.OnIENum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCMNum_BR", DbType="NVarChar(255)")]
		public string CCMNum_BR
		{
			get
			{
				return this._CCMNum_BR;
			}
			set
			{
				if ((this._CCMNum_BR != value))
				{
					this.OnCCMNum_BRChanging(value);
					this.SendPropertyChanging();
					this._CCMNum_BR = value;
					this.SendPropertyChanged("CCMNum_BR");
					this.OnCCMNum_BRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneName", DbType="NVarChar(255)")]
		public string PhoneName
		{
			get
			{
				return this._PhoneName;
			}
			set
			{
				if ((this._PhoneName != value))
				{
					this.OnPhoneNameChanging(value);
					this.SendPropertyChanging();
					this._PhoneName = value;
					this.SendPropertyChanged("PhoneName");
					this.OnPhoneNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailName", DbType="NVarChar(255)")]
		public string EmailName
		{
			get
			{
				return this._EmailName;
			}
			set
			{
				if ((this._EmailName != value))
				{
					this.OnEmailNameChanging(value);
					this.SendPropertyChanging();
					this._EmailName = value;
					this.SendPropertyChanged("EmailName");
					this.OnEmailNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlName", DbType="NVarChar(255)")]
		public string UrlName
		{
			get
			{
				return this._UrlName;
			}
			set
			{
				if ((this._UrlName != value))
				{
					this.OnUrlNameChanging(value);
					this.SendPropertyChanging();
					this._UrlName = value;
					this.SendPropertyChanged("UrlName");
					this.OnUrlNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxWithholdGroup", DbType="NVarChar(255)")]
		public string TaxWithholdGroup
		{
			get
			{
				return this._TaxWithholdGroup;
			}
			set
			{
				if ((this._TaxWithholdGroup != value))
				{
					this.OnTaxWithholdGroupChanging(value);
					this.SendPropertyChanging();
					this._TaxWithholdGroup = value;
					this.SendPropertyChanged("TaxWithholdGroup");
					this.OnTaxWithholdGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxWithholdCalculate", DbType="NVarChar(255)")]
		public string TaxWithholdCalculate
		{
			get
			{
				return this._TaxWithholdCalculate;
			}
			set
			{
				if ((this._TaxWithholdCalculate != value))
				{
					this.OnTaxWithholdCalculateChanging(value);
					this.SendPropertyChanging();
					this._TaxWithholdCalculate = value;
					this.SendPropertyChanged("TaxWithholdCalculate");
					this.OnTaxWithholdCalculateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InclTax", DbType="NVarChar(255)")]
		public string InclTax
		{
			get
			{
				return this._InclTax;
			}
			set
			{
				if ((this._InclTax != value))
				{
					this.OnInclTaxChanging(value);
					this.SendPropertyChanging();
					this._InclTax = value;
					this.SendPropertyChanged("InclTax");
					this.OnInclTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventSiteId", DbType="NVarChar(255)")]
		public string InventSiteId
		{
			get
			{
				return this._InventSiteId;
			}
			set
			{
				if ((this._InventSiteId != value))
				{
					this.OnInventSiteIdChanging(value);
					this.SendPropertyChanging();
					this._InventSiteId = value;
					this.SendPropertyChanged("InventSiteId");
					this.OnInventSiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
